@startuml WeatherAPIcalls

participant FirstLoad [
  =First load
  ----
  GeoLocation started
]

participant LocationByCoords [
  =Geo data
  ----
  Attempt to retrieve
  geo data
]

participant LocationByName [
  =Manual input
  ----
  City name 
  entered manualy
]

participant LookDuplicates [
  =Cities list
  ----
  Dialog if more than
  one city received
]

participant DisplayWeather [
  =Show weather data
  ----
  All weather data
]

FirstLoad -> LocationByCoords : Allow
LocationByCoords -> DisplayWeather : location retrieved
LocationByCoords -> LocationByName : error while retrieving
FirstLoad -> LocationByName : Block
LocationByName -> DisplayWeather : one city in the array
LocationByName -> LookDuplicates : two or more cities in the array
LookDuplicates -> DisplayWeather : correct city was chosen

@enduml